apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./blue-green-app
    repoURL: 'https://github.com/silvertagback/gitops-certification-examples.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    manual:
